trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:
       - task: IISWebAppManagementOnMachineGroup@0
         inputs:
           EnableIIS: true
           IISDeploymentType: 'IISWebsite'
           ActionIISWebsite: 'CreateOrUpdateWebsite'
           WebsiteName: 'test-p'
           WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
           WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
           CreateOrUpdateAppPoolForWebsite: true
           AppPoolNameForWebsite: 'test-p'
           DotNetVersionForWebsite: 'No Managed Code'
           PipeLineModeForWebsite: 'Integrated'
           AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'

