trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:
           
             

        - task: IISWebAppManagementOnMachineGroup@0
          inputs:
            IISDeploymentType: 'IISWebsite'
            ActionIISWebsite: 'CreateOrUpdateWebsite'
            WebsiteName: 'test-1'
            WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
            WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
            AddBinding: true
            Bindings: |
              {
                                                      "bindings":[{
                                                          "protocol":"http",
                                                          "ipAddress":"*",
                                                          "port":"35",
                                                          "sslThumbprint":"",
                                                          "sniFlag":false }]
                                                          }
            CreateOrUpdateAppPoolForWebsite: true
            ConfigureAuthenticationForWebsite: true
            AppPoolNameForWebsite: 'test-pool-1'
            DotNetVersionForWebsite: 'No Managed Code'
            PipeLineModeForWebsite: 'Integrated'
            AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
            AnonymousAuthenticationForWebsite: true
            BasicAuthenticationForWebsite: true