
trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:
       
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Programming'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
          displayName: "ZIPing source files"

        - task: CmdLine@2
          inputs:
            script: |
              echo Write your commands here
              rmdir /s /Q $(Pipeline.Workspace)\drop-Artifacts
              echo Hello world
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop-Artifacts'
            publishLocation: 'Container'
          displayName: "Publish-Build-Artifacts"
          

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: AzureAgentPool
    environment: class16July2024
    strategy:
      runOnce: 
        deploy:
          steps:
          
          - task: CmdLine@2
            inputs:
              script: |
                echo Write your commands here
                rmdir /s /Q 'c:\deployment\'
                echo Hello world
          

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)\drop-Artifacts'
              Contents: '**'
              TargetFolder: 'c:\deployment\'
              CleanTargetFolder: true
              OverWrite: true
              flattenFolders: true
              preserveTimestamp: true
              ignoreMakeDirErrors: true
  
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $zipFolder = "C:\Deployment\"  # Folder where the zip file is located
                $zipFile = Get-ChildItem -Path $zipFolder -Filter "*.zip" -File | Select-Object -First 1  # Find the first zip file

                if ($zipFile) {
                    $destination = $zipFolder  # Unzipping in the same folder
                    Write-Host "Found zip file: $($zipFile.FullName)"
                    
                    # Unzip the file into the same folder
                    Expand-Archive -Path $zipFile.FullName -DestinationPath $destination -Force
                    Write-Host "Unzipped $($zipFile.FullName) to $destination"
                } else {
                    Write-Host "No zip file found in $zipFolder"
                }
                #DISM /Online /Enable-Feature /FeatureName:IIS-WebServerRole /All

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $siteName = "MyApp"                   # Name of the IIS site
                $physicalPath = "C:\Deployment\"  # Physical path for the website
                $appPoolName = "MyAppPool"            # Application pool name
                $bindingInfo = "*:8060:"                # Binding information (e.g., port 80)

                Import-Module WebAdministration

                # Check if the site already exists
                $site = Get-Website -Name $siteName

                if ($site -eq $null) {
                    # If the site does not exist, create it
                    New-Website -Name $siteName -Port 80 -PhysicalPath $physicalPath -ApplicationPool $appPoolName
                    Write-Host "IIS website '$siteName' created successfully."
                } else {
                    # If the site exists, update its properties
                    Set-ItemProperty "IIS:\Sites\$siteName" -Name physicalPath -Value $physicalPath
                    Set-ItemProperty "IIS:\Sites\$siteName" -Name applicationPool -Value $appPoolName
                    Write-Host "IIS website '$siteName' updated successfully."
                }

                # Ensure the application pool exists
                $appPool = Get-Item "IIS:\AppPools\$appPoolName" -ErrorAction SilentlyContinue
                if ($appPool -eq $null) {
                    # Create the application pool if it doesn't exist
                    New-Item "IIS:\AppPools\$appPoolName"
                    Write-Host "Application pool '$appPoolName' created successfully."
                } else {
                    Write-Host "Application pool '$appPoolName' already exists."
                }

                # Set the application pool to use .NET CLR v4.0 (if required)
                Set-ItemProperty "IIS:\AppPools\$appPoolName" -Name "managedRuntimeVersion" -Value "v4.0"
                
                # Set the bindings for the site (if updating is needed)
                Remove-WebBinding -Name $siteName -Port 80 -Protocol "http"
                New-WebBinding -Name $siteName -Protocol "http" -BindingInformation $bindingInfo

                Write-Host "IIS website '$siteName' configured successfully."
                env:
                  SYSTEM_ACCESSTOKEN: $(System.AccessToken)