trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:

        - task: IISWebAppManagementOnMachineGroup@0
          inputs:
            IISDeploymentType: 'IISApplicationPool'
            ActionIISApplicationPool: 'CreateOrUpdateAppPool'
            AppPoolName: 'test-app-pool'
            DotNetVersion: 'No Managed Code'
            PipeLineMode: 'Classic'
            AppPoolIdentity: 'LocalSystem'