# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  jobs:
     - job: 
       steps:
        - script: |
            cd Programming
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            displayName: 'Install dependencies'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: 'Programming\**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true


        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'


