# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:
       

        - script: |
             mkdir $(venv)
             $(buildPython.pythonLocation)\python -m virtualenv $(venv)
          displayName: "Install requirements1"

        - script: |
             call $(venv)\Scripts\activate.bat
             echo "This is really bad."
             echo "A big error has occurred!!"
             exit 45
          displayName: "Install requirements2"



