
trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:
       

        - script: |
             python -m venv antenv
             call "antenv\Scripts\activate.bat"
             python -m pip install --upgrade pip
             pip install setup
             pip install -r requirements.txt
          workingDirectory: $(System.DefaultWorkingDirectory)/Programming
          displayName: "Creating enve and Installing packages"

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Programming'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
          displayName: "ZIPing source files"

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop-Artifacts'
            publishLocation: 'Container'
          displayName: "Publish-Build-Artifacts"
          

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: AzureAgentPool
    environment: class16July2024
    strategy:
      runOnce: 
        deploy:
          steps:
          - task: CopyFiles@2
            inputs:
              sourceFolder: '$(Build.ArtifactStagingDirectory)'  # Path to your built artifacts
              targetFolder: 'C:\Deployment\MyApplication'  # Local deployment path on the server
              contents: | 
                - '**/*' 