trigger:
- main

pool: AzureAgentPool

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:
           
             


        - task: IISWebAppManagementOnMachineGroup@0
          inputs:
            IISDeploymentType: 'IISWebsite'
            ActionIISWebsite: 'CreateOrUpdateWebsite'
            WebsiteName: 'test-my-site-1'
            WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
            WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
            AddBinding: true
            Bindings: 'http/All Unassigned:55:'
            CreateOrUpdateAppPoolForWebsite: true
            ConfigureAuthenticationForWebsite: true
            AppPoolNameForWebsite: 'test-my-site-pool-1'
            DotNetVersionForWebsite: 'No Managed Code'
            PipeLineModeForWebsite: 'Integrated'
            AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
            AnonymousAuthenticationForWebsite: true
            BasicAuthenticationForWebsite: true